spring:
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        password: 
        jedis:
            pool:
                max-active: 8
                max-wait: -1
                max-idle: 10
                min-idle: 2
        timeout: 6000
    application:
        name: dao-server
    cloud:
        nacos:
            discovery:
                server-addr: "127.0.0.1:8848"
                enabled: true
server:
  port: 9429

